### ISSUE TITLE
[EPIC] Realizzazione design

### ISSUE THREAD

**Issue by Byloth** [Bylothink/do-you-dare#13]
Progettare e realizzare un design appetibile con cui sviluppare l'intera applicazione.

Le colonne portanti dell'intero design, sono:
- Tema dark predominante.
- Colori dominanti saturi a contrasto.
- Sfumature con accostamenti di colori eye-catching (evitando colori -tra loro- complementari).
- Oggetti dalla grafica piatta ma molto tondeggiante (nessun effetto di bombatura in 3D).
- Animazioni e transizioni "interattive" con le azioni dell'utente.
- Elevazione degli oggetti e presenza delle conseguenti ombre (non eccessivamente marcate).

---

- [ ] **[Issue #3: Creare l'effetto di carte impilate per il `Deck`](3)**
- [ ] **[Issue #19: Aggiungere i pulsanti per navigare avanti/indietro tra le pagine](19)**
- [ ] **[Issue #39: Rendere il layout responsive](39)**
